export const FETCH_MERCHANTS = "FETCH_MERCHANTS";
export const FETCH_MERCHANTS_SUCCESS = "FETCH_MERCHANTS_SUCCESS";
export const FETCH_MERCHANTS_FAILURE = "FETCH_MERCHANTS_SUCCESS";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const PERSIST_CART = "PERSIST_CART";
export const LOAD_CART = "LOAD_CART";
