export const GET_MERCHANTS = {
  REQUEST: "REQUEST_GET_MERCHANTS",
  SUCCESS: "RECEIVE_GET_MERCHANTS_SUCCESS",
  ERROR: "RECEIVE_GET_MERCHANTS_ERROR"
};

export const FILL_PRODUCTS = "FILL_PRODUCTS";

export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const CHECKOUT = {
  REQUEST: "REQUEST_CHECKOUT",
  SUCCESS: "RECEIVE_CHECKOUT_SUCCESS",
  ERROR: "RECEIVE_CHECKOUT_ERROR"
};

export const GET_ORDERS = {
  REQUEST: "REQUEST_GET_ORDERS",
  SUCCESS: "RECEIVE_GET_ORDERS_SUCCESS",
  ERROR: "RECEIVE_GET_ORDERS_ERROR"
}
