export const GET_MERCHANTS = {
    REQUEST:"REQUEST_GET_MERCHANTS",
    SUCCESS:"RECEIVE_GET_MERCHANTS_SUCCESS",
    ERROR:"RECEIVE_GET_MERCHANTS_ERROR"
}

export const FILL_PRODUCTS = "FILL_PRODUCTS"